package com.kontrol.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

// BACKEND-AGENT: Reddit monitor endpoints.
// Suggestions are generated by the 4-hour scheduled job in RedditMonitorJob.
@RestController
@RequestMapping("/api/v1/reddit")
public class RedditController {

    @GetMapping("/suggestions/{projectId}")
    public ResponseEntity<?> getSuggestions(@PathVariable String projectId) {
        // TODO: return pending/posted/dismissed suggestions for this project
        throw new UnsupportedOperationException("Sprint 2");
    }

    @PostMapping("/post-comment")
    public ResponseEntity<?> postComment(@RequestBody Object dto) {
        // TODO: post approved comment to Reddit via RedditService
        // Accepts: { suggestion_id, comment_text (optional override) }
        throw new UnsupportedOperationException("Sprint 2");
    }
}
